version: "3"
services:
  hfish:
    build:
      context: ./dockerfile
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "9001:9001" # Landing page

      - "21:21"
      - "22:22"
      - "23:23"
      - "69:69"
      - "3306:3306"
      - "5900:5900"
      - "6379:6379"
      - "7879:7879"
      - "8080:8080"
      - "8081:8081"
      - "8989:8989"
      - "9000:9000"
      - "9200:9200"
      - "11211:11211"
